(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"the_eye_atlas_1", frames: [[0,0,432,215]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_1 = function() {
	this.initialize(ss["the_eye_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.dog = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(102,0,0,0.91)").s().p("AnjCUIgTgQIgIgHQgGgKgBgMQAAgQACgPIAFgHIAHgHIAIgIIAjgLIAAgCIAWAGIAPAHQARAPAEAXQAEAZgRAUQgLAHgMAFQgLAFgLACIgXgEgAr7CUIgTgQIgIgHQgGgKgBgMQAAgQACgPIAFgHIAHgHIAIgIIAjgLIAAgCIAWAGIAPAHQARAPAEAXQAEAZgRAUQgLAHgMAFQgLAFgLACIgXgEgAp5BhIgTgPIgIgHQgGgLgBgMQAAgPACgOIAFgIIAHgIIAIgHIAjgKIAAgBIAWAGIAPAFQARAPAEAWQAEAagRATQgLAIgMAFQgLAFgLADIgXgGgALMAbIgTgPIgIgHQgGgJgBgNQgBgPADgOIAFgIIAHgIIAIgHQARgFARgHIABgBIAWAHIAPAGQARAPAEAXQAEAZgRATQgLAHgNAFQgKAFgLADIgXgGgAHmAbIgTgPIgIgHQgGgJgBgNQgBgPADgOIAFgIIAHgIIAIgHQARgFARgHIABgBIAWAHIAPAGQgDgIgBgJQgBgQADgPIAFgHIAHgHIAIgIQARgFARgHIABgBIAWAHIAPAGQARAPAEAXQAEAYgRAVQgLAHgNAFQgKAFgLACIgXgEIgTgQQAIALACAPQAEAZgRATQgLAHgNAFQgKAFgLADIgXgGg");
	this.shape.setTransform(-42.8919,60.55);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.91)").s().p("AvUPEQiEixAHjfQALlHDxjjIAKgIQgGh0gWh0QgLg8gJg8QgNgRgEgVQgDgOAAgPQgLgWgHgXQgGgVgNgRIgCgHQgVAEgOgYQgSAKgPANQgMAJgIANIgKAPQgnAggsAUQiCA9hwhTQgEgEgCgFIgDgGQgBgEgDgEIgHgHIgIgIIAAgHIAAgIIgEgIQgDgHgCgIIgBgOIAAgIIAAgHIAAgIIAFgHIAFgIIAAgHIAAgPIAAgPIABgPIAFgPIAEgIQALiIAYiFQAqjlCEi3QAbgmAqgLQE7gOC6D9QAxBDAtBEQGejbHKBRQDqAqCvCdIACgDIACgHIABgHIAAgIIAHgIIADgHIABgHIABgIIAEgHIAGgIIAFgHQARg8AqgvQAhglAVgsIAQgOIAVgQQAKgWASgSQARgQASgEIARABIAPAEQDPDVBgEeQBODogLD0IgIAHIgTANIgFADQg/ALgzglQgGgEgIgDQghgZgggdIABBrQAAAjgQAgIgHAIIgPAPIgCAHIgBAPIAAAIQATAiAaAfQANAPAKARIACAIIAAAHQAIALAGAMQAFAMAJAJQARAoALArQAGAZgCAbQBGFSjjD8QjWDtkUCuQlgDemaAFIgQAAQoMAAkymYgAu+s0QAFAIACAIQADAMAKAKIAAAHIAAAIIAAAHQAZBLgBBTQgBAbgDAbIAKADQAlA1AMBEQAGAgAUAbQgCAXAFAWQAFAYAMAVQAGBjASBgQAJA0gDA0QiaB/hFC9QgRAtAAAvQgEAHgCAIQgEAOAAAQIgFAHIgDAIQgeG8GFDrQDgCHELAKQHzAUGRk8QB0hbBxhcQByhcBTh6QB+i6gbjsQgDgYgNgUQAFg9gfgzQgTgfgPgdIAAgHIAAgIIgagdIgRgQQgJgOgIgQIgKgWIAAgXIAAglQA2hEgOhaQgHgqARghIAAAAIgKgMIAAgIQAAgHACgHQACgIADgIQAFgEAGgCQATgIAPARQAYAlAnAWQAdASAVAcIARAIIAKAHQAEACAEAAQAPABAPgBIAAgeQAAgTgEgSQgCgIgEgHIAAgeQAAgUgGgSIgEgHQgHhUgVhRQgThLgkhEQgviMhEiEQgshXhOg6IgbAeQgMAOgQAIQgdAtggAqQgaAigVAlIAAAHIAAAIIgDAHIgEAIIgKAPQgHAfgJAeQgMAoggAYQgGABgGgBQgIAAgIgDIgHgHIgIgIIgHgHIgBgIIgEgHQmnloojDGQh+Auh4A6IAAADIAAAHIgCAHIgDAIIgFAIIgIAEQgGACgGgBQgIAAgHgEIgIgGQg5h7hchrQimjCkBAfQhYA7giBtQg5C6gZDBQgCATABATIgFAIQgGAKAAAMIABAXIAAAWIAAAXIgEAHQgFAKgBANQgBALABALIgCAWQgBANgHAKIABAHIAEAIQACAEABAEIADAHIAEAIIAFAGIAKAJIAJAHIAIAIQAFADAFABQA1ADA0AAIASgHQAagKAXgNIAagPIAFgHQAMgRAOgPQAQgQAVgLQANgIAOgGIAJABQAIACAHADQAGADADAFQADACABAEQAAgzgFgzQgEgigBgiQgJgOgDgPQgDgMgFgLQAAgMACgKQAEgSARgDIAPAFgAheOhIgFgEIgRgJIgIgHIgFgFIgCgDQhGgggghJQgFgKACgMQAOgWAXAMIANAHIAEAIQACAEABAEIAAAHQAjAvAyAbQANAHAKALQAuAKAwgRIAQgLQAGgEAIgDQANgMAMgOIAAgBQgKgQAKgOQAEgEAEAAQAIgCAJAAIAAgEIAAgIIADgHIAHgPQAAh/gJh/QgBgYAEgTQghgGgcgZQgsgogugnIgEgQQgCgHAAgHIABgXIAGgHIAHgIIAHgHQBsgXBqgUQAYgBAWAKIAgAOQBPCVi0A0IgEABQAGBngCBrQgCA0AAA1IgFAHIgFAIIAAAHIAAAIIAAAHQgEAKgGAJIAAABIABAIIACAHIAHAIIANAMIACADQAIACAHAEIAIAGQAlALAmgSQBXgvAuhXQAHgOAKgOQAAgXACgWQACgVASgCQAIADAGAEQAEACACAEQAJAQgCAVQgCAPAAAPQgWAwggAoQgLAOgHAPIgDACIgMAGIgDAHIgMAPQgeAXgiARQgHAEgHAGQgyAXg5gNIgSgJIgUgLQgPgTgOgTIgHAHIgOAOQgWAIgRAPIgGAEQgiAPgjAAQggAAghgMgAnkAlQhlhCAOh/QALhrA1hZQAagrAvgRIADgIIAFgHQAOgNATgFQAagGAagEQANgCAHgDQB8AABzAsQAuASAkAhIADAIIACAHIAAAIIAFAHIAIAPIAEAIIADAHQBKEokZBVQg8ASg4AAQhjAAhXg5gAlOmQIgRAFIgXAFQgJAOgQAIIggAQIgMAPQgKAQgNAOIgFAHQgDATgHATQgIAWgDAXQgCALABALQgQAfgBAkQgCA5AaAxQAlAoA3AKQCEAZB5gqQBNgbAhhKIAHhTQAFg9gMg6QgEgNgHgLQgJgQgNgNIgPgPIgMgFIgZgNIgIgEQhegShgAAIgUAAgAHtAAQh+gWhshEQiMhXA7iWIAAgIIAAgHIAHgJQACgDAAgEIABgHQA2hIBVgfQBMgcBNALIAKAIIADAFQAMgCAMgEQAPgEANgIIAIgFIAFgCIAKgCIAAgBQDNgHA6DKQASBCgYBAIAAAIIAAAHIgCAHIgIAQQhLCQimAAQgmAAgrgHgAEElWQgiApgHA4QgBAIgDAHQBcCuDcAHQByAEBag7QAOgKAIgNIADgIQACgHAAgIIADgHIAHgPQAIglgDgmQgHg9ggg2IgfgyIgWgQIgGgEQgzgTg2ALQgcAUgiAGQgbAFgSgSQgPgCgOAAQhoAAhGBXgAlQg8QgIgHgIgGQgNgJgOgIQgOgNgIgRIgFgIQgOgZgJgbIgCgHIAAgIIAAgHIAAgIIAAgHIAAgIIADgHIAAgBIAEALIAIAHIAUAPIAWAFQAMgCAKgFQAMgFALgIQARgUgEgZQgDgWgRgPIgPgHQAKgFAHgBIAUABIAPAEQBVgSBTAaQAYAHANAXIAKAWIAAAIIAAAPIAAAHIAAAIIAAAHIgDAHIgEAIIgDAIIAAAHIAAAIIAAAHIAAAIIAAAHQgDAOgLAJIgIAHIgIAHQgMAKgKANIgPAIIgSAMIgFADQgkAKgkAAQgpAAgngNgAGzhzIgPgFIgHgHIgPgPIgIgIQgEgSACgTIAAgIIAAgHIAAgtQAIgWANgTIAAANQAAAMAGALIAIAHIAUAPIAWAFQAMgCAKgFQAMgFALgIQARgUgEgZQgDgWgRgPIgPgHIgVgGIABAAQAOAAANACIAPADIAKAIIADAEIACADQBLgXAtAzIAKAPIABA0QAABShHArIgFADQgSACgSAAQg4AAg1gUgARjn2QgVgggNgjQgHgTABgTIgDgIIgEgIIgDgHIAAgHIAAgIIAAgPQgFgHgDgJQgCgGAAgIIAHgHIAGgEQAEgDAFgBQAMADAKAEQAFACADAEQAGAKAAAMIgBAeQANAoAUAnQAKAUAHAVQgHAWgUAAQgJAAgLgEg");
	this.shape_1.setTransform(-59.5377,29.3908);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-200.7,-107.8,282.29999999999995,274.4);


// stage content:
(lib.theeye = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(153,153,153,0.91)").s().p("Ag5AXQADgGAGgEIAPgMIARgJQARgMAVgFQARAAARABIABACIABACIAAADQAAAEgCACQgWANgbgCQgHAEgFAGQgQAQgTAAQgIAAgJgDg");
	this.shape.setTransform(155.775,248.8371);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(153,0,0,0.91)").s().p("AB5CCIgHgHQgCgDAAgDQAAgDADgBIACAAIAXAVQAEAEACAGIgDACIgEABIgSgRgAAKCGIgCgCQASgHATgKIADgCIADgBIADgBIAAgBQAFgBACAFIAAADQgWARgaAAIgDAAgAgQBuIgDgCIABgBIACgDIACgBQATAAAUABIAEACIAAACIgBACIgBABIgCAAIgLAAIgegBgAB0BjQgHgFAIgEQAOAEAMAHQAFADACAGIgHABQgMAAgPgMgAgdBSIABgCIABgBIABAAIACgBIAkAAIADABIACACIACAEIAAACIgBAAIgRACQgQAAgOgHgABEAgIAAgIIgDgBIgEgBIgQgLIAAgGIAAgFIgBgBIgBgCIABgFQAAgBABAAQAAgBAAAAQABgBAAAAQABAAAAAAQAEABACAEIACAEIAAACIAAAGIANAKIgBgJQAAgHADgFIAAgCIAAgCIAAgCIAEgCIADgCQAIAEgFAJIgDAEIABATIAAABQAHgHALgEQADgFAFgEIACgCIACAAIACgBIAAAAQAEAAABACIAAAEIgJAJIgCACQgJAHgKAEQgGAAgBgEQAAAFgCAEIgGABIgCgBgABkAbQABgFAIAAIABgCIACgBIACgBQAEgBABAEIABAEQgFAFgHACIgCAAQgFAAgBgFgAiVgqIAAgCIAAgCIAAgCQADgCABgDIABgEIAAgCIAAgCIAbgiIAPgVQAPgKAMgOQAFgFAGgBQAEABAAAEIgBAEQggAYgYAhIgRAXQAAAFgCAFQgCADgDACIgFABIgDgBgAhGgsQgKgCgJgFIgCgCIgCgEIgBgCIAAgCIAAgBIABgCIAEgEIACgCIADgBIAEgBQAQgRAUgMQAUgLAWgEIAlAAIADABIABACIADAGIADADIAAACIAAACIAAAEIgCACIgBACIAAABIAAACIgCACIgBACIgBABIgBABQgYANgbgBIgCACQgUAPgWAMIgMgCgAgphaIgQAKIgQANQgFAEgDAGQAcAKAXgXQAGgGAHgFQAaACAXgNQABgDAAgDIAAgEIAAgCIgCgBQgRgCgQAAQgVAGgSALg");
	this.shape_1.setTransform(158.225,256.975);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(153,102,0,0.91)").s().p("AoxB8QgQgFgJgGQgggBgfgIQgXgGgJgPIAAgBIg3gTIgigOQgegCgegKQgPgFAFgHIACgCIgTgGIgYgFIABgBIAQABQgEgEAFgEIA0AJIAHAAIAIAAQAUgPAegFIAYgFIgEAAIg5gDIAgAAIgCAAIALAAQApgCAogHIAIgHIgsgCIgBAAIgHAIIgFAFIgCABIgVgGIADgCIARgGIABgBIgKAAIALAAIAGgGIAFgFQAigMAlgIQAjgIAigNIAAgCQAQABAQAEIAAADQg8AQg+APQgXAGgVAJQAZgBAYgDQAPgNARgHQgBAHgHAJQAXgFAXgGIADgBIgdgBIAAgBIABgCQBWABBWAEIAAADIgCABIiLgFQgRAYglgBIgKAAIgBABIAGAAQgIAHgKAEQBGgFBEgOQAKABAKAEIAAADQg5APg5AEIgEAGIABAAIAJAFIApgDIAXgMIACAAIACAAQgGAHgHAGIgOAIIgPAGICiAEIAAADIgCABQhEAChFABQAZAKAbAFQAVAEAVAHQgqAAgpgLQAHADAGAFIAPADQgMACgLABIgEAAIAGAEQAGAFAFAHQALAFAJAGQhJgJhJgZQgYgIgLgJIhGgDIA2AMQAZAFAVAIIABgGIALAIQAkAMAkAOIAIAEIAEAAQAiACAVARIAJABQAcAFANAMQgqgBgtgHIgUACQAaAKAdACQAmADAYAVQg9gEg+gVgArsAtIAUAEIgFAAQARAEAQABQAyABgHAfIAwAJIALACIABgBQgLgGgCgJIAJACIgHgCQgkgLgFgOIh3gUIAUAJgAomA8IgMgIIgEgDQgwgKghgMIgLAAIgEAAIgBABQAyAaA6AGIAFAAIAAAAgAsiAjIgIgEIAUABIgNgCIgZgFQAMAHAOADgAo4AdIAKACIgOgFIAEADgApMAaIgBgCIgJAAIAKACgAqTAOIAAgBIgEABIACAAIACAAgArwAJIgQAEIAHAAIAcgEIgRgBIgCABgAqHALIAFAAIACgBIgHABgAqrADIgHAGIgDABIAdgFIgRgBIAAgBIABgCIAdABIAVgEIAKgDIAAgDIAEABIAGgDQgZACgYAAIgBAAIgOAGIgGADIgDACgApoACIAAgBIgBABIABAAIAAAAgAqtgHIgDAEIAAAAIAHgEIgEAAgAsVBwQgbgJASgJQAcAWAoAEQAYADAXALQgygDg4gTgAJyBPQASgRAbgPQARgJAQgHQgsAIguAEQgDABgCgDQAjgUAtgCQAYgCAXgEIgZgFIAAABIgCABIiDgGIAAgBIABgCQA+ABA9AEQgjgJACgPQAjgCAgANQALAEAIAGIACgBIALgDIhGgUQglgJAPgSQAbASAhABQAoABgEAZIAJgCQgFAKgIAJIADAFIgHgBQgHAGgJAGQgSAKgGgNIgBAAQAEAPgUADIgVAEIgcASQgKAGgLAFIgHABIgEAAgAKkBAQApgHAkgWIAGgEQAXANgwAOQgOAEgOAHQgJAFgHAAQgKAAgEgKgANjAdQgEgHgJgDQgvgyg0gtIAAAAIgDgBQgEgCgDgEIgEgHQgIgKgOgFQgZgIAKgMIACgDQAPANAPAMQAAgHAFgFQAHAHAEAIQACADAAAEIARAIQARAeAZAXQAQANARALIAFAIIADAGQATAGAIASQACACgCAEIgEABQgFAAgFgIgALEg+QgjgLANgPQAcARAfAGQAZAEgJAVQgYgMgdgKgAoVg8IgygFIB2gUQAEAAADgDQgDAegwAAIgYgCgAp1hVQAfgKAhgHIARgFIAAgBQAyABAyAEIAAADQg/gGg+AOIg8AMQACgEACgBgALph5QgSgMARgFIAUAPIAZAPQgDAEgFAAQgMAAgYgRgAqXiHQA0gCArgLQAIABAGAEQABAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQghALgfAAQgXAAgXgGg");
	this.shape_2.setTransform(142.1125,269.425);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(153,153,153,0.91)").s().p("AAaFCIAAgBIAAgBIACgCIADgBQADABABAEIgCADIgHgDgAgMj4IgFgDIgCgCIgCgDIgDgDIgCgJIgFgMIgBgLIgCgJIABAAIAAABIADADIAEAAIACAAIACgCIADgDIAAgCIAAgCIAAgCIAAgCIAEgFIAEgGIACgCIADgCIADABIAEADIAAABIABADIACACIAAACIACADIAAACIAAAPIAAAPIACACIAAACIABAJQABAHgDAEQgIAFgKAAIgBAAg");
	this.shape_3.setTransform(162.15,297.55);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(153,0,0,0.91)").s().p("AhyB4IgJgFQgDgDAAgDIgDgCIgCgCQAAgDgBgDIgDgHIgBgCIAAgCIAAgCIgBgCIgCgCIgBgLIgBgRIABgCIABgBIAAgCIAAgCIABgCIABgCIACAAIAFACIAAACIABAEIAAADIAAAAIACgCIABgDIAAgEIABgCIABgCIAAgCIAKgJIAJgGIAFAAIAGAEQADACADADIABACIAAACIABACIACACIAAABIAAACQAEAJgCAKQgBAKAEAJIAAALQAAAJgBAIQgMALgPAAIgHgBgAiCBEIABALIAFAMIACAJIACACIADAEIACABIAEAEQALAAAJgFQAEgEgBgHIgBgJIgBgCIgBgCIAAgPIAAgPIgBgCIgBgEIgBgCIgBgBIgBgDIAAgBIgFgDIgDgBIgDACIgDACIgDAGIgEAFIAAACIAAACIAAACIgBABIgDAEIgBABIgCABIgFgBIgCgCIAAgBIgBAAIACAJgABmBDQgJgIAJgFIAeAYQAGAFAEAGIgDACIgGABQgQgLgPgOgAAPBSIgCgBQAAgHADgFQACgEAEgBQAJAFgGAIIgEAFIgDAAIgDAAgAgWBIIgEgBIAAgCQABgFAFgEIACgCIACgCIAAgCIABgCQAFgEAHgBIAMgCIAAgBIAKABIAFACIAAACIgBACIgBABQgMAAgLAEIgDABIgDAEQgEAFgFAEIgBACIgDAAIgCAAgAhFAuIABgBIAEgEQAOgEAPgCIASgDIACAAIAZABIAEACIAAACIgBACIgBABQgYAAgYAGQgKADgIAAQgIAAgHgDgAA/gKIgDgBIAYgrQADgFAFgEIADgCQAHADgEAGQgCADABADQgLAOgJAPQgEAGgFAFIgCABIgDgBgAAtgvIgCgGIAAAAIAAAAIgBgCQgEgUgIgTIgHgRIABgFQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAgBQAOAXAIAbIAMgPQAEgFAFgCQAEABABAEQAAADgCACQgLAGgFANIgEAHQACAKAFAIIADAEIACAEIgCACQgCABgDAAQgJgIgEgMg");
	this.shape_4.setTransform(171.975,261.5531);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(153,102,0,0.91)").s().p("AovB/IgMgHQggAEghgHQgjgIgYgNIABgBQAkgDAjAHIASADIgTgIQgNgGgOgDIgJgHIg2gSQgigMgXgLQgXgBgXgIIAjgHIg3gDQAlAAAkAAIAOgDQgOgIgIgIQgcAGgdAKQgIgBgJgEQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAgBgBAAQCFgoCIgdQBTgQBRgWIAUgQIAHgHQAWgCATgKQAFAHgFAFQAOAHgbAIIgWAIIgIAIIgIAHIgJAEIABAAQAcgGAZgIQhOAghtAjQBugLBsgUIAJgDIgDACIAGgCIAAAAIgLAFQglAUgpAQIAHABIAAADIg3AMIglAIIAfAGQA/gCA/ABQACAAACADQhsANhwgEIgbAMQgIAAgJgDQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIAVgIIgegBQgWADgagCIgTABIgbAGIAqALIACAAQgNgEgHgIIABgBIAtAKIADAAIAAAAIAAAAQA+ACA+AEIAAAEIgBACIAaAAIAGAAIgBABIBHACIAAADIgDABIhIgCIgDACICJAJQhLAEhKgFIgOAFIAVABQAmAAARARIgUAAIBVAHIgbAEQAjAHAgAJQg6gBg7gMQgjAAgkgDIAWAHQAcAKAUAKIgZAAIgqgSIAWAKQgYgCgbgEQAoAUAuAIQAWAEAIAMIgKgCQAMAEAIAIQhRgBhMgjgAnNCPIgtgNQgOgEgHgEIgLgCQAkAQApAHgAocBzIAIADQgCgCAAgDIgGACgAopBsIAEACIAPACIACgEIgkgGIAPAGgAolBLIgGgBIACABIACAAIACAAgApPBKIAKAAIgHgHIgegHIhDgKIBeAYgArQAeQgNAEgMACIAGABIAoAAIgTgHIgCAAgAoAALIAUAAIAOgBIgNgBIgIgBIgNADgAreALIAOgDIgogHIAaAKgAofALIAFAAIAGgBIgLABgAsAgBIAHACIAiACIgLgDIgTgBIAMgDIgDgCIgUAFgAoegxIABADQhVAThUAWIAcAFQAmgKAlgLIgJgBIAOgBIBAgUIARgMIgVAGgAoMgUIgiABQgQAIgTAIIAxgKIAAgBIABABIAbgIIgIABgAn9gWQgKALgMAHQApgHApgJIANgEIAJAAIAdgJIAggKQhBAQhOAFgAq1gQIgoAHIAJACIAtgLIgOACgAmFhtQg2Abg5AUIgJAJIAYgJQAhgNAegJIABAAIAPgFQAKgJAIgLIgBAAgAmqByQgFgHAHABIACAAQAKAFAJAGQAGAGAGAIQgYgDgLgQgAMugCIABgCQAQABAPAEQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAIgJAAQgTAAgDgKgAMsgnQAAAAABgBQAAAAAAAAQABgBAAAAQABAAABgBIACAAQAAABAAABQABAAAAABQABAAAAAAQABAAAAABIAaAJIAAADQgNAGgIAAQgOAAAAgTgAMtgvQgVgIACgHIABgCQAKABAHAFQAEAEACAIIgFgBgApog9QAOgLAQgFIgpgEQBugQBgg3QAOgHAQgCQgwAshSAWIgmALQAGACAFACQABABAAAAQAAAAAAAAQAAABAAAAQAAABAAAAQgeASglAAIgCgCg");
	this.shape_5.setTransform(136.5,269.05);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(153,153,153,0.91)").s().p("Ag9CEQgvgSgUguIAAgCIAAgHIgBgGIgBgCIgEgCIgCgBIAAgCIgBgEIgBgCIAAgBIgBgGIgCgEIAAgRQgBgJgEgIIAAgMIAAgJIAEgIQAGgIAIgFQAJgDAIADIAFAEIAKAHIAHANIALAVQAAAKADAKQAFATAJASIAAACIAAACIABABIAAACIABACIADACIADAJQADAEAAAEIABACIABACIAAAUQAAAOgFANQgFAAgDgCgAAVBCIgCgBIAGguQABgLAHgGQAJAUgKAZQgEAJgBAJIgEABIgCAAgABjA0IAAgCIgBgBIgKgOIgFgFQgGgPgLgLQgJgHAJgEQATAPAPAXQAGAJACAKIgCADIgFABIgCgCgAgmArIgCgBIAAgDIAAgGIABgCIABgCIACgCIAAgCIABgDIAAgCQgCgDAAgDIAAgCIAAAAIgFACIgEADIgFAEIAAACIAAACIAAAEQgEAEgEAAIgFgCIgBgBIAAgCIACgDIABgBIACgCIAAgCIAAgBIAAgEIACgCIAFgCIACgCIABgCIAdgOIADgCIAHgBIAEgCIADABIAEACIAAACIAAACIgBABIgHACIgFABQgJAFgLAGQAJADgBAJIgCAIIgBACIgBACIgBABIgBACIAAAEIgBACIgEAAIgCAAgABngBQgBgBAAAAQgBAAAAgBQAAAAABgBQAAgBABAAIADgCQAQAFAPAHQAHADADAHIgDACIgEABIglgTgABDhTIgBgBIABgCIACgDIgHAFQgFACgDgEIAAgBIABgEIACgCIAEgCIATgSIAFgEQAIAMgVAOIgBAAIAGgCQAHACgEAFIgEAEIgEABQgCAAgDgCgAAThVIgBgEIgCgGIAAgCIAAgDIAAgCIgBgCIgBgCIAAgFQABgEADAAQAHADAAAJIABAGIAAACIACADIAAACIAAACIAAACQgCADgDAAQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAgAAkhaQgBgQABgPQABgJAJgDQAHAEgEAJIgDAHIAAANQAAAFgBAFIgCABIgHgBg");
	this.shape_6.setTransform(184.625,266.275);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(153,0,0,0.91)").s().p("AgCBQIgPgOQgBgEgDgDQgJgJgFgMIgEgIIgBgBIAAgEIAAgGIAAgCIgBgBIgDgCIgCgCIgBgCIAAgBIAAgCIgBgCIgCgCIAAgCIAAgBIAAgCIAAgCIAAgBIgBgCIgBgCQAAgJgCgKQgEgUABgVIAAgEIAFgIQAHgKAMgHIACgBIASAAIADABQAHAEAGAFIAFAEQAOAUAFAYIAHAYIgCAEIAAABIABACIAEABIAJATIAAACIAAACIACADIAFAMIAGANIAAAFIAAARIgBANIgBACIgBACIAAACIgBAHIgGAKIgBAAQgcAAgWgUgAgehZQgIAFgGAIIgEAHIAAAKIAAALQAEAJABAKIAAARIACAEIABAFIAAACIABABIABAEIAAABIACACIAEACIABABIABAGIAAAIIAAABQAUAuAuATQADABAFAAQAFgMAAgOIAAgVIgBgCIgBgCQAAgDgDgEIgDgJIgDgCIgBgCIAAgCIgBgCIAAgCIAAgCQgJgQgFgUQgDgKAAgLIgLgUIgHgOIgJgHIgFgDQgEgCgEAAQgEAAgFACg");
	this.shape_7.setTransform(174.84,270.5006);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(153,102,0,0.91)").s().p("AARCFIgPgGIgPgBIBAASQhigEhfgeQhagKhOgEQA6gEA5gBQghgNgggQQgqgVAHgPIAsAWIAAAAIABgCIACAAQgWgMgMgQQAAAAAAAAQABAAAAAAQABAAAAAAQABAAABABIAKACIgFgCIAcgBQgTgDgTgGQAdAEAYgCQgHgGACgIQAQAFAQAFIAPgGIgFAAIAAgBIAKAAIAFgDQAIABAHACQAaAAAagBQAXgMAegCQAHAAAGgDIABgBIgaACQgbACgaAMIgogHIBDgQIgPgEQgXAIgaAGQgaAGgbAFQAggQAlgOIgTgFICIgnIABgBQAigJAjgHIASgLQgTAAgQgDIAZgGIhTgCIgBgCIBugDIAwgLIAMgDIAQgEIAmgIIBngYQAJABAIAEIAAADIhNAUIACAAIhMAUIAkAAIADAAIACAAQgCAGgDAAIg/ACIgrAMIgKAEQBGgLBHACQg4AUhcAOIAEAAIAYgEIgKAEQBGgDA/gOQAaABAaAEIAAADQhhAOhhgCQgVAIgYAHIAygHIAEAAQgVARgoACQgMAIgPAGIAJAAQAdgIAegFIgjANICAADIAMgEIgBAEIAHAAIAagHQAegIAXgQQgSASgWAOIAFAAIAAADIgCABIgIgBQgiAVgqAIQghAHgcANIAPgMQgNADgPgBIgJAAIgGACIgIgCQgGADgGAAQgzAHgzAEIAQAGQA4gDA4AKQAdAFAeADQgYAVglgGIgMgCIANAGIAGABIC2gJQhJAPhkAEIAFAFIgCABIgSgBIgCgEIgVAAIgHAAIgRABIACADIgKgDIhXAAQAeAIAgAHQAQAEALAEIAgAFQgQgGgKgHQBEAGBDAMQAiAGAXAOQgrgEgugGIAnAKIgpAAIABAAIgXgBIgFAAQAuAMAuAJQAuAJAeALQh2gCh0gngAhSBfIALABIgsgLQAQAGARAEgAiKBcIAEAAQgwgPgvgVIgOgHIgHAAQA3AZA5ASgAhkBMIBNgDIgZgHIghgJIAAAAIgNgEIhOgCQAjAOAlALgAi0AzIABAAIAAAAIAAAAIgBAAgAjRApIASAGIBSABIgFgBQgXgDgWgGQgNgEgKgFQgcAGgZgEIAaAKgAgMgIIgjAEIgBABIgfAIIgtAMQAQABAOADQAzgFAzgEIgkgCQAcABAbgCIgBAAQBAgOA/gVIh/gCIg3ATIATgDIAAgBQAVACgXADgAiyALIABAAIAAAAgAieACIAAACIgMAFIACABIA0gJIAAAAIgqABgAgfgWIgBAEIAfgKIACAAIgFgBQgMAFgPACgAA1hJQg0AIgzALQgXALgcAKIBFgRIgBAAIADgBIA8gOIAjgIIgIAAIgEAAgAgggoIgRAEIAwgLIgBAAIgeAHgAAIAdIAAgBIABgCQAQABAQAEIAAADIgCABIgfgGgAghhQIAHAAIgHAAgABjiUIAKgHIAIgFIACAAIACAAIgNAOIgJAIQgZAKgcADQAMggApAJg");
	this.shape_8.setTransform(86.125,267.925);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(153,153,153,0.91)").s().p("AhOCQIgBgBQgVgMgRgOIAAgGIAHgNIAAgCIABgCQBHAbBLABIAGAJQAKANgDAMQgSACgSAAQgtAAgvgOgAAyAXIgOgQIgGgDIgDgDIABgBIABgBIABAAIACgBIAAAAQAZANAUAZQAHAJAFAJIgCADIgFACQgRgRgPgTgAhMAMIgDgDQABgGAHAAIADgBIAFABIAEACIABACIgBACIgBABIgJACIgDABIgEgBgAA0gKQgCgCAEAAQARAGASADQAHABAEAFIgCADQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgYgEgSgNgAhvgPIgDgDQAYgMAegCIAFABIAFACIAAACIgBACIgBABIgqAHQgGABgGADIgFgCgABIgmIgCgCQATgJAZgCQAEABAAAEIgBAEQgQAEgQAAIgNAAgAgThHQgHgWgEgXQgCgKgFgJIgFgRQgBgFAEAAQALALAEASQABAHADAGQgBAFACAFIABAHQAEAFABAGIABAIIABACIABACIAAACQgBAEgDAAQgCAAgDgCgAAUhJIAAgEIACgEQABgNgCgNQAAgGgEgFIABgLQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAAAQAIACAAAJQgBADACACIADAeQABAHgDAGQgCACgDAAQgCAAgDgCg");
	this.shape_9.setTransform(161.7667,269.8373);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(153,0,0,0.91)").s().p("AhcAAQgCgCAAgDIAAgFIAAgEIACgCIABgCIAAgCIAAgCQACgCABgDIABgCIABgCIgBgCIgCgEIABgDIACgDIACgBIADABIACABIACAAIAFAAIADACIACADQBDAcBJgBQAJAHAGAJQAGALABANIAAAEIgDADIgCAEIgCABQgUADgUAAQhMAAhAgtgAhNgbIAAACIgHAMIAAAGQARAOAVALIABABQBAAVBAgIQADgNgKgNIgGgHQhLgChHgaIgBACg");
	this.shape_10.setTransform(158.47,282.2802);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("rgba(153,102,0,0.91)").s().p("AmbClIgfgIIg9gBQgRAAgNgIQgKAAgJgCIgSgBQiKgHiJgEQgeAAAKgOQAOAEAOAAQCBAFCCACQAWABANAIIgBgBQgCgDABgCQABgDAEgBQAPAIAQACIAoAHQgMgHADgHQAwASAyACQAzACAnASQgRACgTAAQgnAAgugKgAKCClQAAAAAAAAQAAAAAAAAQAAgBgBAAQAAgBAAAAQBTgbBKgvIAKgGIgxACQgNANgYAOIgXAQQADgXAbgRIAFgDQg9ABg+gBIAAgCICJgFIAFgCIgMgDIAEgBIiwgEQgKgHgJgHIACgBIACgBIACgCQAHAEAGAAIDWAHIASgFQAUgGANgKQAOAMgbAKIAPAAIAUACIAPgEIgHAFIAEABIAGgGQAPgNARgEQgLAOgOANQAIADAHAFIgWgBQgaAXgfAQIgpAWQgHAAgHgDQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBgBAAAAQAxgTApghIgNABQgzAehDAfQgeAOgfALQgJAAgIgDgAMBBNIA2gCIADgBIgugBIgLAEgAo2BuQgQgEAGgEIgygBIABgCQiAgDh/gcQgogIAWgKIAmAKIBUACQgEgFAFgHQARAEASAAIBQABIARgGIgLACQgXAEgLgMQANgGAOgDQhMAChNgCQBlgBBigSIB4gxQAOgGALgJQgsAyhSAUIgPAGIApgGIAAgBIAIAAIAZgKIAYgKQAKABAKAEIAAADIgtAKIgDAEQAggEAggGQAPgEAHgIIgBAHIALgCIA3gOQAJABAIAEIAKgCQhDAwhfADQgUAAgQgDQgPADgOAFQgJgBgIgEIAAAAIgaAKIBTgCQAJAAAIgDQAKABAKAEIAAADIgZAFIgBAAIAmABIASABIAAADIgCABIgEAAIgBAAIg5gCIgGAAIgMADIAWAIQgQAAgPgFIAAAAQhaAWhbgXQgLgDgGgEIhLgBQBmAYBrADIAWAAIAGgBIAZAAIAAAAIARAAIA0ABICrACIAIAEIANAHIABAEIgCABQgLgDgMAAQhqgBhqgCQA7APA/AGQAnADAaALQhfgJhigTgAMOAhQgUgCgKgHIgTgBIAAgBIABgCIAOABIABgBIADABQAlABAlADIAAADIgCABIgugDIAEABIBKALQglAAglgFgAM6g2QgYgcgfgTIgEgIIgDgFIAAgCQgZgOgTgWQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQgKgHgHgIIACgDIADACIARAGIAEAHIACAFIABADQAuAlAuApQAKAJALAIQAWAdASAfIAPAdQgcgkgtgzgAMGgaIgPgDQAQAVgUgNQgKgHABgFQgYgLACgMIAAgDQAGABAFAEQAFAEAEAGQAqAEAkAWQAMAHAHALIADAEQgFAEgIAAQgWgagjgIgALYhTQgogYADgWQAvAkA0AeQAcAQAVASQgvgOhAgogAsRh0QghgLAPgJQBBAeBJAHQAfADAfAFIgaAAQhOAAhOgZg");
	this.shape_11.setTransform(133.6065,265.528);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("rgba(153,153,153,0.91)").s().p("AA0CQIgIgHQgEgEgDgFIgBgCIAAgCIADgFIACgEIACgCIAAgCIAAgCIABgCIAFgFQAJgNACgPIABgIIABgCIABgCIAAgHIABAAIAAACIAAAGIAAAEIAAACIACABIAFgBIACgBIAAgCIAAgCIAAgCIAAgCIACgCIABgBIAAgCIAEgFQADgDACgDIABgCQAIgEAFgHQAXgaAgAOIABACIABACIAAACIAAACQAEAHgCAIIgDAPIgBACIgBANIAAAHIAAACIgBACIgBACIAAACIgCALIAAAHIAAACIgBACIgCACQAAAHgEAFIgHAJIgBACQgEACgEADIgHAIIgDACIgWABQgVAAgVgGgAA2AvQgSgBgQgTIgUgZIAAgCIAAAAIABgBIACgBQAUAPAUASIAMAMIAEAEIgCAAIgDAAgAhpAlIgDgBIAAgCIABgDIABgCIAFgEIAEgCIABgCIAAAAQgVAJgWAGQgMAEgHgIQAngMAogRIAAgBQAFgBACAFIAAADIgLAGQABAAAAAAQABABAAAAQAAAAABABQAAABAAAAIAAAEIgFACIgDACQgDAFgFADIgEADIgDABIgCgBgAgogwQgCgdgEgeIgDgEIgLgNIABgDIADgCIAAAAIAJAHQABgJAFgGQAFAOADAPIAIALQANgJAKgNIABgCQAFgGADgJIADgGQAAgDABgCIADgCQALAPgRAUQgFAGgGAEIgPAMIgCABQAGAIADAIIgCACQgBABAAAAQgBAAAAAAQgBABgBAAQAAAAgBAAIgFgGIgCgCIgGgHIABAOQABANgDAMIgGAAIgCgBg");
	this.shape_12.setTransform(139.6333,272.275);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("rgba(153,0,0,0.91)").s().p("AgkBKQgTgFgMgQIgBgCIgBgCIgBgCIAAgBIAAgCIAAgCIAAgEIAAgCIABgCIABgCIABgBIACgCIACgCIAAgCIAAgCIABgCIABgCQAGgHAEgIIAGgKIAAgCIAAgEIAAgFIAAgCIABgCIABgCIAAgCIABgKIAFAAIgEgEQABgHAAgHIgBgCIgBgCIgBgBIABgCIACgBIAEAAIAFACIAAAEQABAKgCAKIgBAIIAAAHIgCACIgBACIAAAIQgCAOgJANIgGAFIAAACIgBACIAAACIgBACIgDAEIgCAFIgBACIABACQADAFAFAEIAHAHQAgAJAggEIACgCIAIgIQADgDAEgCIACgCIAGgJQAEgFABgHIABgCIABgCIAAgCIABgHIABgLIABgCIABgCIABgBIAAgCIAAgHIAAgNIABgCIAEgPQACgIgEgHIAAgCIAAgCIgCgCIgBgCQgggOgWAaQgEAHgIAEIgCACQgBADgEADIgEAFIAAACIgBABIgBACIAAACIAAACIAAACIgBACIgBABIgFABIgDgBIAAgCIAAgEIAAgGIAAgCIACgBIABgCIAAgCIABgCIACgCIAEgEQADgCAAgDIACgCIAIgEIAEgCIAEgFQAMgNAQgGQALAAAKABQAGABAGACIACACIADADIAEAGIAAACIAAACIABABIABACIABACIAAACQAAAHgBAGQgBAJgDAIIAAACIAAAHIgBANIgBABIgBACIAAACIAAACIgBAIIgBALIgBACIgBACIgBABIAAAEQgWAqgqAAQgOAAgQgEg");
	this.shape_13.setTransform(149.3583,280.5939);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("rgba(153,102,0,0.91)").s().p("AKPDKIBQgUIAUgFIAOgMIBShHIAAAAQAYgVAcgQIADgHIADgDIACgCIABgBIABgCQAKABAJADQAFACADAEIACADQgNgBgQADQg4Aug5ArQgOALgNAMIgUAVQgvAOgwACQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBgBgBgAIlCoQgBgBAAAAQAAAAAAAAQAAgBAAAAQAAgBAAgBQA+gRBAgVQA7gSA3gaQglAgg3AUIA2gHQArgXApgYIguACIgPABIgbANIgGAEQgPACgPAAQgCAAgDgCQAIgGAKgFIg1AIQgIABgJgEIADgCIARgKIAvgEIAVgDIATgCIAAgBIANAAIARgFQAJgQAQgHQAIgFAHgFIAAgCQAWACgXANQgJAGgKAEIgHAHIgFAIIgDABIAtAEIAQgKQAOgJANgDQgSARgVAOQgVAOgYALQgcANgaAPIg1gEQgUAGgWAFQgsALgrAPQgIgCgGgCgAo9CRQgNgDAGgHIAEAAQACACADAAIAsAJIABAEQgYAAgXgFgAqoCRQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAgBAAgBQAUgOAcgJIgHgEIABgBIAAgCIATADIALgCIAfgFQAfgEAfABQgGAHgIACIgaAGIBaAHIAAACQg3AAg3gBIgDAAIgMgBIgZAFIgXADQgGACgDAFQgBABADAEIgKAAQgMAAgMgCgAoEBZIg9gCIgqgEQgQgBgMgCIgKAAQhSgBhSgEQgDAAgBgDQgBgEABgEIABAAIADgCQAEAEAEAAICaAKQgOgFgFgHIg4gOIgZgCQgcAGgcAEIgJABIgHABQAFgNAJgIIAFgEIgGAAQg+gBg9gJQA9ACA8gEIAGgBIAAAAIACAAIASgBQgOgBgNgFQAbgFAcgHIAAgBQAKABAJAEIABADQgNAGgNADQB3gMBygiQgCAhhpAQIgHACIAbADIAAACQgWAAgVABICPAHIAAACIgBAAIgxAAIgDABIhSAGQAIAGgCALQBAAFA+ALQAZAEAZAHIglgBgAJqBKQBggMBWgeQAGAZhKAPQggAGgcABIgHAAQgZAAgWgFgAN5AhIgCgBQgDgBgCgEIgEgIIgXgYIgRgSIgPgNIgHgHQgwgqg3gfIgBgBIgOgCQgTgRgYgGQAQALATAHIARAQIAmAlIARAOIAYAHQAPAEAMAIIAHAFQAHAGAGAIIgWgBIgMgBIAAABIAMAMIAHAIIAJAKIAFAGIAAAAIALABIAAACIgKAAIgDAAIgeACIgBAAQgiADgiAHQgaAFgagJQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIADgCIAKgCIAFgDQAXgOAdgBIAAgBQAfADAfAFQAIACAHAEIAHAAIgRgPIgFgDIgWgUIgwgEQhTgJgvgMQAqgFApABQAYAAAYAEIAOACIgCgBQgjgLgYgOQgOgIgKgIIAXACIACACQAXALAYAJIgogkIgGgGQgrgng3gQIgIgHIgFgFIg+gZQgOgGAOgCIArAOQASAEALAPQAVAFASALIAJACQghgVgUgWQAfAOAfAXIATAQIAJADQAJAFAJAGQAqAMAmAUQAcAQARAWIgXgKQAQAMAPAOIANAOIACACQAdAcAUAjIgGgCgANBguQgDgIgGgGIgBgCIgIgIQgSg/hDgQQg4gMAJgYQAjAUAlAPIAjAQIAPAPIAIAHQAGATAKAQQAMAUAMARQgFAEgEAAQgHAAgEgKg");
	this.shape_14.setTransform(134.975,266.35);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("rgba(153,153,153,0.91)").s().p("AAQBKIgQgSIABgCIADgCIA3AvQALAJAJAKIgCACQgCACgDAAQgfgVgZgbgABqBYQgEgDgEgEQgCgCAAgDIgCgFIAAgCIAAgDIgBgBIgBgCIgBgCQABgMgBgLIgDgfIgFgQIgFgZIgEgLQgCgJgGgIIAAgBIAAgCIAAgDIgBgBIgBgEIAAgCIACgFQAEgGAGgEQARAAARACQAMABAFALIAAACIAAAFIAAAEQACADAAAEIAAAGQADAGABAFIAEAOIAAACIAAABIAAACIACAIIAAAGQAEALAAAOIgBAtIgBACIgBABIgBACIAAACIgBAFIgBAFIAAACIAAABIgBACIgDAEIgCACIgTABIgGgDgAh9A9QAGgHAMgDIALgCIAAAAIAKABIAFACIAAACIgBACIgBABQgNABgNAFIgFABIgDABIgCABQgFAAgBgFgAiOAvIAAgBIBBgPIAEABIAFADIAAABIgBACIgBABQgaAJgaAAIgUgBgAg2gTIgBgBIgBgDQgKgJgFgLQgDgFAEgCQgHgRgEgTIgEgYQgCgDAAgDQAAgEAEgBQAMAPADAVQAFAjAUAbIAAABQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgBABIgHAAIgCgCgAgegmIgBg3QAAgNAIgIQAGARgCAYIgCAhQgCAEgCAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAgBAAg");
	this.shape_15.setTransform(112.3028,270.85);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("rgba(153,0,0,0.91)").s().p("AgMBZIgBgCIgBgCIgBgCIAAgBIAAgCIgBgCIgBgCIgBgCIAAgCIAAgCIAAgBIgBgCIgBgCIAAgEIgCgcIgBgXIgBgBIgBgCIgBgCIAAgCIgBgHIgEgLIAAgCIAAgCIAAgCIgBgBIgBgCIAAgCIAAgCIAAgCIgBgCIgEgLQgDgIgEgHIgCgCIgCgCIgBgCIAAgBIABgCIABgCIAAgCIAAgCIAAgCIAAgCIAAgCIACgCIABgBIAAgCIACgCIABgCIACgCIAAgCIADgCQAFgDAGgBIAAgBQAagFAUAMQAIAEAFAIIAAACIAAAEIAAADIAAAEIABACQACADAAADIAAAFIAAACIABACIABACIAAACIAAACIAAACIABABIADAIQACAFgBAGQAHAWABAWQACAogQAjIgEACQgIADgIAAQgRAAgMgNgAgkhPIgCAFIAAACIABAEIABACIAAACIAAACIAAABQAGAIACAJIAEAMIAFAYIAFAQIADAgQABALgBALIABACIABACIABACIAAACIAAACIACAFQAAADACADQAEAEADACIAGADIATgBIACgCIADgEIABgCIAAgBIAAgCIABgEIABgGIAAgCIABgBIABgCIABgCIABgtQAAgOgEgLIAAgGIgCgIIAAgBIAAgCIAAgCIgEgNQgBgGgDgGIAAgFQAAgEgCgEIAAgDIAAgGIAAgCQgFgLgMgBQgQgCgRAAQgGAEgEAGg");
	this.shape_16.setTransform(122.6358,270.7358);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("rgba(153,102,0,0.91)").s().p("AIQEAIAAgBIABgCQAuABAuAEIAAADIgCABIhbgGgAJKDsQBeghBZgxIAlgVQAIABAGAEQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAABIg2AXIAHAAQAHAAAIgEQAKgFAHgCQAcABAbAEIAAADQgsgFgnARQgVAKgTAHQgFACgHgBQACgGAEgFQgjAQgiATIg2AcIgXgHgAHuDOQAwgdA6gaQgtANgpATIgSgCQBGgdBPgUIAVgJIgGAGIAWgFIBBgOQhagCh2AEQgsABgqANQgOAFgPAAQACgDADgBQAegKAegIQARgFASgDIAPgDIAlgFIAmACQAtgSAwgJIi1gCIADgCQA/AAA2gLQAqgEAqADIgGgFQhRgThVgPQhIgMglgbQB5AaB5AcIAUAFIgYgXIgogbQgdgHgegFQhjgQgZgcQBOAPBMATIgMgKQgWgSgFgPIgBgBIgqggIgigHQhYgTg/gWIAFAAQBFADBDAOIgHgEQgWgDAEgKIgLgHIhngDIAAgBIABgCIBfACIgXgOIgFgIIgDgFIgUgEIABgBIAQACIgEgEIgMgFIgNgFIgDgHIgEgGIgzgNQgSgEAIgMQAAAAABAAQAAAAAAAAQABgBAAAAQABAAAAAAQAdAUAiALQASAGARALIAHAIIABACQBmALBeAwIAGABIAIAGIAHAEQATAKAPAOQATAMAUALQANAIABAKIgCABIgHAAIASAJQAzAZAmAhIAHADIgDADIAAACIAAAHQgCADgCAAQgDAAgCgCIgBgHQgpgYgrgdIgKgHIgegHIgUgPIgKgIIghgHQgIgIgKgGIgGgCIAJAGIhGgOIAbAVQAAgGADgGIADAHIACAIIBKA8IAoALQAtANAkAeQgtgUgzgNIAWARQAWARAUATIAXAKIAOgDIgJAGIAEACIgFgCIgBABQAKAEAGAHIglgBIgCAAIABABIAGAMIgKgLQghAOguAJIgIACIBcAGIAQABIArgMIAQgJIACADIAIgCIAAgBQAIANglAQIAJABIgLAAIggAKIgSAGIgKAFQghAgg2ARQgyAQgegNQBMgHA8gnIgBAAQgsAMguAJQAogSAqgQQggAGggAHQgnAdg7AZQgcAMgUAAIgEAAgALkA1IAOACIAMACIgdgHIADADgALXAmIAQAGIgWgNIAGAHgALAhMIAEACIgHgHIADAFgAK2hRQgQgRgUgPIgMgFQgNgGgJgJQg+gMg9gEIAGAEIACgBQAeAIAdAJQgBgDAHgEIAsAYIABABQAmAOAlAQIAAAAgAHiijQAvALAyACIANABIgwgSIhIgCIAKAGgAGtjGIAlAYIBCACQg1gSgzgKIABACgAsDCHQg/gJgagLIAAgCQASgCASAAQgRgJABgQIACAAIAuAOQgDgCACgGQgBgDADgCIAAgBIABgDQAVABAVAEIAAADIgGABQALAEANADQAVAFAVAHQgaAJgcgGQgKgCgHgGIgFACIAcAJQAaAJAbAFIgQAAQgXAGgXAAQgNAAgNgCgAsVBlIAAgBIgBAAIABABgApuB+Qg8gJgbgWIgBgBQgXgFgPgHIg1gGIAAgBIABgCQAWABAWACIgEgDQAzABAyAKQATAEAKAKQAAgEACgDIACgDQgkgBALgMIABgCQAQABANAHQADACAAAIIgEAHQgJAPAAgMQgaABgfgEIANACIBBANQADANgLAAIgEAAg");
	this.shape_17.setTransform(137.125,261.225);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},1).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9}]},1).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12}]},1).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15}]},1).to({state:[{t:this.shape_15},{t:this.shape_16},{t:this.shape_17}]},4).wait(1));

	// Layer_2
	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#000000").ss(1,1,1).p("AgKAsQgJgDgIgIQgMgMAAgSQAAgEABgEIi/gvQAIgmAVghQAOgXAUgUQA/g/BXgFAhgDXQgmgRggggQhFhFAAhhQAAgbAGgZADXhgQAUAsAAA0QAAAPgBAPQgKBOg6A6Qg+A+hVAHQgJAAgKAAQg0AAgsgUAAkgWQAJALAAAOQAAACAAABQgBAQgMALQgDAEgEACQgKAHgNAAQgGAAgGgCIhWCrAgZgcQAMgKAPAAQASAAAMAMQACACACACICzhKAgmgFQACgMAJgJQABgBABgBIivhfAAtAGIC9AYAANjqQBZAEBABAQAgAgARAmAAZAnIgGDE");
	this.shape_18.setTransform(165.1,264.225);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#009900").s().p("AhiCgIBWirQAGACAGAAQAMAAAKgGIgFDCIgTABQg0AAgsgUgAAqgwIAAgDQAAgPgJgLIC0hLQAUAsAAA1QAAAQgCAPgAjohrQAJgnAVghICvBgIgCACQgJAJgDALg");
	this.shape_19.setTransform(165.375,269.775);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#00D40C").s().p("AAaAnIAHgFQAMgMABgPIC9AXQgKBOg6A7Qg+A9hVAHgAilCnQhFhGAAhhQAAgaAGgaIC/AvIgBAIQAAASAMANQAIAHAJADIhWCsQgmgRgggggAAhgaQgMgMgSAAQgPAAgMALIivhgQAOgXAUgTQA/g/BXgGQgRAKgTAJQABAAAAABQAAAAABAAQAAABAAAAQABAAAAAAQAJABAIgBQANgIAOgDQAMgEAGgGQBZAEBABBQAgAfARAmIizBLIgEgFg");
	this.shape_20.setTransform(165.025,264.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgfAUQgBAAAAAAQAAgBgBAAQAAAAgBgBQAAAAAAgBQASgIAQgJIAEgDQAPgJAQgHQACALgHAIQgGAFgNAEQgMADgNAIIgJAAIgIAAg");
	this.shape_21.setTransform(163.3829,240.825);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#333333").s().p("AgMAoQgKgDgHgHQgMgMAAgSIAAgIQADgMAJgJIACgCQAMgLAPAAQASAAAMANIADAEQAJALAAAOIAAADQgBAQgLALIgIAGQgKAHgMAAQgGAAgGgDg");
	this.shape_22.setTransform(165.35,264.55);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f().s("#000000").ss(1,1,1).p("AhfDXQgmgRggggQhFhFAAhhQAAgbAFgZQAJgmAVghQAOgXAUgUQA/g/BWgFAANjqQBZAEBBBAQAfAgASAmQAUAsAAA0QAAAPgCAPQgJBOg6A6Qg+A+hVAHQgKAAgKAAQg0AAgrgUAAkgWQAJALAAAOQAAACAAABIC9AYAgYgcQAMgKAPAAQARAAANAMQACACABACIC0hKAgJAsQgKgDgIgIQgMgMAAgSQAAgEABgEQADgMAIgJQACgBABgBIivhfAAtAGQgBAQgLALQgEAEgEACQgKAHgMAAQgGAAgGgCIhWCrAAZAnIgFDEAgmgFIi/gv");
	this.shape_23.setTransform(177.95,263.525);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#333333").s().p("AgMApQgKgEgHgHQgMgNAAgRIABgJQACgLAJgJIACgCQAMgLAPAAQARAAANANIADAEQAKALgBAOIAAADQgBAPgLAMIgIAGQgKAGgMABQgGAAgGgCg");
	this.shape_24.setTransform(178.2,263.85);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#00D40C").s().p("AAaAoIAHgGQAMgMABgQIC9AZQgKBNg6A7Qg+A9hVAHgAilCnQhFhFAAhiQAAgaAGgaIC/AvIgBAJQAAARAMANQAIAHAJADIhWCrQgmgRgggfgAAhgaQgMgMgSAAQgPAAgMAKIivhfQAOgXAUgTQA/hABXgFQgRAKgTAIQABABAAABQAAAAABAAQAAABAAAAQABAAAAAAQAJABAIgBQANgIAOgDQAMgEAGgGQBZAEBABBQAgAfARAmIizBLIgEgFg");
	this.shape_25.setTransform(177.875,263.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("#000000").ss(1,1,1).p("AjHh7QANgXAUgUQBAg/BWgFAhgDXQgmgRggggQhEhFAAhhQAAgbAFgZQAIgmAWghADYhgQAUAsAAA0QAAAPgCAPQgKBOg5A6Qg/A+hVAHQgJAAgKAAQg0AAgsgUAANjqQBZAEBBBAQAfAgASAmAgKAsQgJgDgIgIQgMgMAAgSQAAgEABgEQACgMAJgJQABgBABgBQANgKAPAAQARAAANAMQABACACACQAJALAAAOQAAACAAABQgBAQgLALQgEAEgEACQgKAHgMAAQgGAAgHgCIhWCrAAZAnIgGDEAAkgWIC0hKAAtAGIC9AYAgmgFIi/gvAgZgcIiuhf");
	this.shape_26.setTransform(135.5,269.725);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#333333").s().p("AgMApQgJgEgIgHQgNgNAAgRIABgIQADgMAJgJIACgCQAMgLAPAAQASAAAMANIAEAEQAIALABAOIAAADQgCAPgLAMIgIAGQgJAGgNABQgGAAgGgCg");
	this.shape_27.setTransform(135.75,270.05);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#00D40C").s().p("AAaAoIAHgGQAMgMABgPIC9AYQgKBNg6A7Qg+A9hVAHgAilCnQhFhFAAhiQAAgaAGgaIC/AvIgBAJQAAARAMANQAIAHAJADIhWCrQgmgQgggggAAhgaQgMgMgSAAQgPAAgMALIivhgQAOgXAUgTQA/hABXgFQgRALgTAHQABABAAABQAAAAABAAQAAABAAAAQABAAAAAAQAJABAIgBQANgIAOgDQAMgEAGgGQBZAEBABBQAgAfARAmIizBLIgEgFg");
	this.shape_28.setTransform(135.425,269.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f().s("#000000").ss(1,1,1).p("AgjAUQACgLAJgJQABAAABgBQALgLANAAQAQAAAMAMQACACABACQAIALAAAPQAAABAAACQgBAPgKAMQgDADgEADQgJAGgMAAQgFAAgGgCQgIgDgHgHQgMgNAAgRQAAgFABgFIivgtQAIgnATghQANgWASgUQA6g/BPgGAi1CbQgig5AAhIQAAgaAFgZAAXBCIgDCAAgWgBIihhgAgJBGIg4B6ADGhGQASAsAAA0QAAAQgCAPQgIBOg1A6QgIAIgIAIAAMjQQBRAEA8BBQAcAfARAmAApAhICtAYAAhAEIClhK");
	this.shape_29.setTransform(106.825,270.025);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#333333").s().p("AgLAoQgJgDgGgHQgMgMAAgSIABgIQACgMAJgJIABgCQALgLAOAAQAQAAAMANIACAEQAJALAAAOIAAADQgBAQgKALIgIAGQgIAHgMAAQgFgBgGgCg");
	this.shape_30.setTransform(107.05,273);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#009900").s().p("AgeCGQgUAAgRAJIA4h6QAFACAGAAQALAAAJgGIgDCAIgJACQgQgIgWgFgAAngPIAAgDQAAgPgJgLIClhLQASAsAAA1QAAAQgBAOgAjUhKQAHgnAUghICgBgIgCACQgIAJgCALg");
	this.shape_31.setTransform(107.075,274.925);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgcAUQgBAAAAAAQAAgBgBAAQAAAAgBgBQAAAAAAgBQARgIAOgJIAEgDQAOgJAOgHQACALgGAIQgGAFgMAEQgLADgMAIIgIAAIgHAAg");
	this.shape_32.setTransform(105.2347,249.275);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#00D40C").s().p("ABdDBQgOAAgMAEIgPgEIgOABIgGgBIgMABIADiAIAIgGQAKgMABgPICtAYQgJBOg0A6IgQAQQgUgJgZgHgAiJCjIgOABQgNgFgQgEQgig5AAhIQAAgaAFgZICvAtIgBAKQAAARAMANQAGAHAJADIg4B6IgDACQgZgTgtgMgAAfAAQgMgMgQAAQgOAAgLALIighgQANgWASgUQA6g/BPgGQgPALgSAIQABAAAAABQABAAAAABQAAAAABAAQAAAAABAAQAHABAIgBQAMgHAMgEQALgEAGgGQBRAEA8BBQAcAfARAmIimBKIgCgEg");
	this.shape_33.setTransform(106.75,270.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_22,p:{x:165.35,y:264.55}},{t:this.shape_21,p:{x:163.3829,y:240.825}},{t:this.shape_20,p:{x:165.025,y:264.2}},{t:this.shape_19,p:{x:165.375,y:269.775}},{t:this.shape_18,p:{x:165.1,y:264.225}}]}).to({state:[{t:this.shape_25},{t:this.shape_19,p:{x:178.225,y:269.075}},{t:this.shape_21,p:{x:176.2329,y:240.125}},{t:this.shape_24},{t:this.shape_23}]},1).to({state:[{t:this.shape_20,p:{x:188.675,y:262.25}},{t:this.shape_21,p:{x:187.0329,y:238.875}},{t:this.shape_19,p:{x:189.025,y:267.825}},{t:this.shape_22,p:{x:189,y:262.6}},{t:this.shape_18,p:{x:188.75,y:262.275}}]},1).to({state:[{t:this.shape_20,p:{x:160.975,y:266.2}},{t:this.shape_21,p:{x:159.3329,y:242.825}},{t:this.shape_19,p:{x:161.325,y:271.775}},{t:this.shape_22,p:{x:161.3,y:266.55}},{t:this.shape_18,p:{x:161.05,y:266.225}}]},1).to({state:[{t:this.shape_21,p:{x:133.7829,y:246.325}},{t:this.shape_28},{t:this.shape_19,p:{x:135.775,y:275.275}},{t:this.shape_27},{t:this.shape_26}]},1).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29}]},1).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_30},{t:this.shape_31},{t:this.shape_29}]},1).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_30},{t:this.shape_31},{t:this.shape_29}]},1).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_30},{t:this.shape_31},{t:this.shape_29}]},1).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_30},{t:this.shape_31},{t:this.shape_29}]},1).wait(1));

	// Layer_1
	this.instance = new lib.dog("synched",0);
	this.instance.setTransform(129,433.05,0.5402,0.5042,0,0,0,-59.5,29.4);

	this.instance_1 = new lib.CachedBmp_1();
	this.instance_1.setTransform(17.25,206.8,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(10));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(167.3,506.8,66,-4.600000000000023);
// library properties:
lib.properties = {
	id: '4E7323B0DE84441B981B45D661E5367A',
	width: 300,
	height: 600,
	fps: 7,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/the_eye_atlas_1.png", id:"the_eye_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['4E7323B0DE84441B981B45D661E5367A'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;